Write a function so that the columns of the output matrix are powers of the input
vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

#Solution 1
def Alex_Vander_Matrix(input_Array, col, increasing = False):
    rows = input_Array.tolist()
    b = []
    for i in range(len(rows)):
        if not increasing:
            for j in range(col):
                b.append(rows[i]**(col-j-1))
        if increasing:
            for j in range(col):
                b.append(rows[i]**j)
    output_array = np.array(b)
    output_matrix = output_array.reshape(input_Array.size,col)
    
    return output_matrix  

In [2]:
Alex_Vander_Matrix(np.array([1,2,3,4,5]), 4)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]])

In [3]:
Alex_Vander_Matrix(np.array([1,2,3,4,5]), 4, increasing = True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   4,  16,  64],
       [  1,   5,  25, 125]])

In [4]:
#Solution 2
def Alex_Vander_Matrix_2(input_Array, col, increasing=False):
    
    if not increasing:
        output_matrix = np.array([x**(col-1-i) for x in input_Array for i in range(col)]).reshape(input_Array.size,col)
    elif increasing:
        output_matrix = np.array([x**i for x in input_Array for i in range(col)]).reshape(input_Array.size,col)
    
    return output_matrix

In [5]:
Alex_Vander_Matrix_2(np.array([1,2,3,4,5]), 4)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]])

In [6]:
Alex_Vander_Matrix_2(np.array([1,2,3,4,5]), 4, increasing = True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   4,  16,  64],
       [  1,   5,  25, 125]])

Question: Write a function to find moving average in an array over a window:          
        Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.


In [7]:
def moving_average(input_Array, window):
    a = input_Array.tolist()
    b = []
    for i in range(len(a)-window+1):
        sum = 0
        for j in range(window):
            sum = sum+a[i+j]
        b.append(sum/window)
    moving_avg = np.array(b)
    return moving_avg
        

In [8]:
moving_average(np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]), 3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])